# Generated by Django 4.1.5 on 2023-01-29 04:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='dff71c99825dfe6fac78e82b73e66a61', max_length=255, null=True, verbose_name='healthycrops'),
        ),
    ]
